---
title: "1. Sammendrag"
format: html
---

# 1. Sammendrag

Rapporten viser utgiftsutviklingen i folketrygden i perioden 2015–2025 og framskrivinger til 2035 samt hvordan befolkningsendringer og regelendringer påvirker utviklingen. Det er befolkningsendringer som påvirker mest, men også regelendringer har hatt betydelig innvirkning.

Målt i realverdi i 2026-kroner[^1] har utgiftene til folketrygden økt med 113 milliarder kroner fra 2015 til 2025, til 736 milliarder kroner. Fra 2025 til 2035 venter vi at utgiftene vil øke med ytterligere 95 milliarder kroner til 831 milliarder kroner. Som andel av fastlands-BNP tilsvarer det en økning fra 15,4 prosent i 2015 til 16,0 prosent i 2025. Fram til 2035 ventes andelen å øke vesentlig til 17,3 prosent. Veksten i utgiftene på statsbudsjettet har vært sterkere enn veksten i folketrygdens utgifter de siste årene. Som andel av statsbudsjettet har derfor folketrygdens utgifter gått ned, fra 35,7 prosent i 2015 til 33,9 prosent i 2025. I 2026 venter vi at andelen vil øke noe igjen, til 34,4 prosent.

Økte utgifter til alderspensjon utgjør en stor del av utgiftsveksten. Her har utgiftene i realverdi økt med 65 milliarder kroner siden 2015, til 351 milliarder kroner i 2025. Fram til 2035 venter vi en ytterligere økning på 56 milliarder kroner. For helsetjenester har realveksten vært 9 milliarder kroner, og vi venter en ytterligere realvekst på 15 milliarder kroner (31 prosent) til 61 milliarder kroner i 2035. 6 milliarder kroner av veksten gjelder legemidler, mens 8 milliarder kroner gjelder andre helseformål. Veksten skyldes befolkningsvekst, økt etterspørsel etter helsetjenester og legemidler, flere behandlere og vridning mot nye og dyrere legemidler.

Utgiftene til helserelaterte trygdeytelser, det vil si sykepenger, arbeidsavklaringspenger og uføretrygd, har fra 2015 til 2025 økt med 42 milliarder kroner til 269 milliarder kroner. Veksten kan i hovedsak forklares av økte utgifter til uføretrygd og sykepenger, der økningen har vært henholdsvis 25 og 15 milliarder kroner. Samlet er veksten 18 milliarder kroner høyere enn hva befolkningsvekst og endret alderssammensetning av befolkningen skulle tilsi. Fram til 2035 ventes utgiftene til disse ytelsene å øke med 20 milliarder kroner til 289 milliarder kroner. Det er rundt 10 milliarder kroner mer enn hva befolkningsendringer tilsier. Det skyldes en trend de siste årene med særlig høy vekst i bruken av arbeidsavklaringspenger, og som også gir økt tilstrømming til uføretrygd. Sykefraværet har også økt mye, men her venter vi ikke ytterligere økning.

Befolkningsvekst og endret alderssammensetning kan forklare størstedelen av utgiftsveksten i folketrygden, og det skyldes særlig aldring av befolkningen. Befolkningsendringer har bidratt til 108 milliarder kroner av utgiftsveksten på 113 milliarder kroner fra 2015 til 2025, og ventes å bidra til ytterligere 102 milliarder kroner av forventet utgiftsvekst på 95 milliarder kroner fra 2025 til 2035. Regelendringer har gitt en innsparing i 2025 sammenliknet med 2015 på 33 milliarder kroner. Dette gjelder i stor grad alderspensjon der regelendringer har gitt 34 milliarder kroner i innsparing, hvorav pensjonsreformen har gitt en innsparing på 39 milliarder kroner, mens andre regelendringer (økt grunnpensjon, og flere økninger av minste pensjonsnivå) har gitt merutgifter på 5 milliarder kroner.

Av utgiftsveksten fra 2015 til 2025 er det 38 milliarder kroner som verken kan forklares av befolkningsendringer eller regelendringer. Her gjelder 20 milliarder kroner alderspensjon, og det skyldes særlig effekten av at økt sysselsetting blant kvinner har gitt høyere pensjonsopptjening. Også for uføretrygd, sykepenger og legemidler har utgiftene økt klart mer enn befolkningsendringer og regelendringer skulle tilsi, og dette utgjør henholdsvis 8, 6, og 5 milliarder kroner på disse ordningene. Dette skyldes høy tilstrømming til uføretrygd blant personer som har mottatt arbeidsavklaringspenger (særlig i årene før koronapandemien), sterk vekst i sykefraværet, og økt forbruk av legemidler samt vridning mot nye og dyrere produkter. Dagpenger og stønader til enslige forsørgere har økt 6 og 3 milliarder kroner mindre enn hva befolkningsvekst og regelendringer tilsier. Det skyldes lavere arbeidsledighet, samt nedgang i fødselstall og antall enslige forsørgere, samt at enslige forsørgere jobber mer enn tidligere.

Fra 2025 til 2035 vil vedtatte regelendringer og pensjonsforliket bidra til en utgiftsnedgang på 50 milliarder kroner. Det gjelder hovedsakelig alderspensjon (-51 milliarder kroner), uføretrygd (+1,9 milliarder kroner) og stønader til enslige forsørgere (-1,3). For alderspensjon gjelder dette i hovedsak pensjonsreformen og pensjonsforliket i 2024. For uføretrygd gjelder det pensjonsforliket (som gir økt øvre aldersgrense for uføretrygd) og økningen i fribeløpet til 1 G. For stønader til enslige forsørgere gjelder det at ordningen blir avviklet for hovedgruppen av mottakere fra 1. juli 2026. På andre områder er det bare mindre endringer som i sum ikke har vesentlige effekter.

Utgiftsendringer som verken kan forklares av befolkningsendringer eller regelendringer, utgjør 44 milliarder kroner av utgiftsveksten fra 2025 til 2035. Det gjelder først og fremst alderspensjon (+24 milliarder kroner, som skyldes fortsatt økende pensjonsopptjening), helsetjenester (+10 milliarder kroner, som skyldes at vi venter fortsatt høy vekst i etterspørselen etter både legemidler og andre helsetjenester) og helserelaterte ytelser (+8 milliarder kroner, som skyldes at vi fortsatt venter betydelig vekst for arbeidsavklaringspenger og uføretrygd).

