---
title: "Innledning"
format: html
---

# Innledning

Rapporten viser utgiftsutviklingen i folketrygden i perioden 2015–2025 og framskrivinger til 2035. Formålet er å beskrive hvordan veksten i folketrygdens utgifter har påvirket handlingsrommet i statsbudsjettet fram til i dag, og hvordan det er anslått å bli påvirket fram mot 2035.

Rapporten gir grunnlag for å tenke mer langsiktig om politikkutformingen utover det enkelte budsjettåret. Enkelte tiltak, for eksempel endringer av satser som påvirker alle mottakere, vil ha en stabil utgiftseffekt allerede i løpet av ett til to år. Andre tiltak som bare gjelder for nye mottakere, vil gradvis kunne øke i effekt over lang tid. Slike tiltak er det særlig viktig å forstå konsekvensene av. Økte utgifter til alderspensjon har vært og vil være den viktigste driveren bak utgiftsveksten på lang sikt.

Selv om utgiftene blir sterkt påvirket av befolkningsvekst og endret alderssammensetning, viser rapporten at politiske tiltak også har en betydelig effekt. De kostnadsdrivende elementene av pensjonsreformen bidro eksempelvis til betydelige merutgifter fram til 2020, mens de kostnadsbesparende elementene av reformen anslås å bidra til at veksten i utgifter til alderspensjon fram mot 2035 vil bli betydelig lavere enn den ellers ville ha vært.

Rapporten er skrevet av Arbeids- og velferdsdirektoratet og Helsedirektoratet i samarbeid med Arbeids- og inkluderingsdepartementet, Barne- og familiedepartementet, Finansdepartementet og Helse- og omsorgsdepartementet.

## De viktigste endringene fra 2025-rapporten

Vi oppgir her de viktigste endringene i framskrivingene fra tilsvarende rapport i 2025, [Nav (2025)](https://www.nav.no/no/nav-og-samfunn/kunnskap/analyser-fra-nav/nav-rapportserie/utviklingstrekk-i-folketrygden-20132033), som omhandlet folketrygdens utgifter i perioden 2013–2033:

- Folketrygdens utgifter i 2033 anslås nå til 815 milliarder 2026-kroner, mot 778 milliarder 2025-kroner i fjorårets rapport. Målt i samme kroneverdi er de nye anslagene rundt 3 milliarder kroner lavere enn i den forrige rapporten. De største endringene gjelder legemidler (-6,7), arbeidsavklaringspenger (+6,1), alderspensjon (-6,0), uføretrygd (+4,4) og stønader til enslige forsørgere (-1,4).

  - For alderspensjon skyldes det noe lavere anslag for veksten i antall alderspensjonister. Omleggingen av AFP i offentlig sektor fra 2025 har hittil gitt en svakere vekst i antall mottakere av alderspensjon enn forutsatt, og dette påvirker også prognosene framover.

  - For legemidler skyldes anslagsreduksjonen først og fremst flere tiltak for å begrense utgiftsveksten til enkelte fedme- og diabeteslegemidler.

  - For arbeidsavklaringspenger skyldes det først og fremst et klart høyere anslag for antall mottakere. Det skyldes sterkere vekst enn antatt i 2024 og 2025, og at vi venter at veksten også vil fortsette i 2026. Vi tror dette blant annet skyldes at både pandemien og pressede ressurser hos Nav til oppfølging og saksbehandling har ført til forsinkelser i avklaringer, og at de nye reglene fra 1. juli 2022 gjør at brukere som når maksgrensene for ytelsen, har mulighet til å fortsette med arbeidsavklaringspenger. Høyere sykefravær og at flere enn antatt derfor går fra sykepenger til arbeidsavklaringspenger, spiller også inn.

  - For uføretrygd er forklaringen også høyere anslag for antall mottakere, og dette henger særlig sammen med økt anslag for arbeidsavklaringspenger, som medfører at flere enn antatt også går over til uføretrygd.

  - For stønad til enslige forsørgere skyldes reduksjon avviklingen av ordningen for hovedgruppen av mottakere fra 1. juli 2026.

- Folketrygdens utgifter som andel av statsbudsjettet anslås nå til 33,9 prosent i 2025, mens fjorårets rapport anslo 35,1 prosent. Delvis skyldes dette at folketrygdens utgifter i 2025 endte 1 milliard kroner lavere enn antatt, men hovedforklaringen er at utgiftene på statsbudsjettet ble høyere enn antatt på andre områder.

- Folketrygdens utgifter som andel av fastlands-BNP i 2033 anslås nå til 17,0 prosent, ned 0,4 prosentpoeng fra fjorårets rapport. Anslaget for folketrygdens utgifter er bare marginalt endret, og dette skyldes hovedsakelig at anslaget for BNP i 2033 er oppjustert. Årsaken er at SSB har gjennomført en [hovedrevisjon av nasjonalregnskapet](https://www.ssb.no/nasjonalregnskap-og-konjunkturer/nasjonalregnskap/artikler/nasjonalregnskapet-revideres-i-2024), der de reviderte tallene for fastlands-BNP er høyere enn tidligere, og som derfor gir høyere anslag for BNP også framover.

::: {.callout-note}
Forutsetninger og metoder for framskrivingene

Omregning til 2026-kroner

Alle utgiftstallene er oppgitt i 2026-kroner1, og følgende deflatorer er brukt ved omregningen:

-
Sykepenger, dagpenger og foreldrepenger2: Lønnsutviklingen

-
Alderspensjon3, arbeidsavklaringspenger, uføretrygd, etterlattepensjoner og stønader til enslige forsørgere: Utviklingen i folketrygdens grunnbeløp (G), som hovedregel tilsvarer også dette lønnsutviklingen.

-
Legemidler, grunn- og hjelpestønad, hjelpemidler, stønad ved gravferd: Utviklingen i konsumprisindeksen (KPI).

Andre helseformål: Utviklingen i KPI og lønnsutviklingen (vektet henholdsvis 0,3 og 0,7).

I praksis medfører omregningen til faste 2026-kroner at utgiftsutviklingen illustrerer vekst i antall mottakere eller i volum og underliggende endringer i utbetalinger per mottaker som ikke skyldes prisregulering av ytelsene4. Bruk av ulike deflatorer for ulike ytelser gjør det krevende å sammenlikne utviklingen for ulike ytelser over tid, og medfører at man ikke direkte kan se hvor mye budsjettmessig handlingsrom den enkelte utgiftsart tar opp. Derfor er det i vedlegget også laget en alternativ framstilling der folketrygdens utgifter er vist i faste 2026-priser, deflatert med konsumprisindeksen.

Framskrivinger til 2035

Utgiftsframskrivingene bygger på anslag fra Beregningsgruppa for folketrygden laget til regjeringskonferansen i mars 2026 om Statsbudsjettet 2027. Disse framskrivingene går til 2030, men er i denne rapporten forlenget til 2035.

Framskrivingene bygger på et vidt spekter av modeller og metoder, blant annet tidsserieanalyser, demografiske framskrivinger og mikrosimuleringsmodeller. På kort sikt er det ofte lagt til grunn videreføring av trender de siste månedene eller de siste få årene. Prognosene for de helserelaterte ytelsene bygger på kort sikt på framskrivinger av tidsserier for antall personer som starter å motta, slutter å motta og beveger seg mellom de ulike ytelsene. På lengre sikt bygger framskrivingene for de fleste områdene på hovedalternativet i befolkningsframskrivingene fra Statistisk sentralbyrå. Det er da oftest lagt til grunn at andelen av befolkningen som mottar de ulike ytelsene vil holde seg konstant framover i hver ettårig aldersgruppe. I tillegg er det tatt hensyn til regelendringer (inklusive vedtatte endringer i Statsbudsjettet 2026) og andre kjente forhold som vil påvirke utgiftene. Effekter av pensjonsforliket i 2024 er også inkludert i framskrivingene, selv om ikke alle detaljer rundt de nye reglene er avklart. Det får betydning for alderspensjon fra antatt innføringstidspunkt 2028, og for sykepenger, arbeidsavklaringspenger, uføretrygd og dagpenger fra 2033.

Dekomponering av utgiftsutviklingen i ulike forklaringsfaktorer

For folketrygden totalt og innen hvert hovedområde er både utgiftsutviklingen 2015–2025 og forventet utvikling fram til 2035 dekomponert i tre ulike forklaringsfaktorer som til sammen forklarer utgiftsendringene:

-
Befolkningsendringer: Angir hvor mye av utgiftsendringene som kan forklares av endringer i befolkningen – både befolkningsstørrelse og endret alderssammensetning.5 Dette er basert på beregninger av hva utgiftsendringen ville ha blitt fra 2015 til 2025 gitt at andelen av befolkningen i hver ettårig aldersgruppe som mottar hver enkelt ytelse hadde vært den samme som i 2025, og gitt at også gjennomsnittlig utbetaling per mottaker i faste 2026-priser hadde vært som i 2025. Tilsvarende er det beregnet hva utgiftsendringen vil bli til 2025, også gitt at samme andel av hver aldersgruppe mottar ytelsen som i 2025 og gitt samme utbetaling per mottaker som i 2025. For enkelte av ytelsene er det brukt noe forenklet metodikk for å anslå konsekvensene av befolkningsendringer.

Mange ytelser, særlig de som er knyttet til aldersgrenser, vil følge befolkningsutviklingen nokså tett. Andre ytelser knyttet til helsetilstand vil mer indirekte være knyttet til alderssammensetningen. Lengre levealder vil trolig innebære bedre helse, som kan føre til en redusert vekst i utgiftene til blant annet arbeidsavklaringspenger og uføretrygd. Slike forhold er vanskelig å anslå effekten av. Dette inngår derfor ikke i beregnet effekt av befolkningsendringer, men vil i stedet medregnes under «andre endringer» omtalt under.

-
Regelendringer: Angir hvor mye av utgiftsendringene som kan forklares av regelendringer6. Effektene framover i tid gjelder effekter av allerede vedtatte regelendringer og pensjonsforliket i Stortinget.

-
Andre endringer: Angir hvor mye av utgiftsendringene som verken kan forklares av befolkningsendringer eller regelendringer. Denne faktoren vil fange opp endringer i tilbøyeligheten til å motta ytelser eller i utbetalingene per mottaker i faste 2026-priser. Dette kan skyldes ulike forhold. Endring i tilbøyeligheten til å motta de ulike ytelsene kan for eksempel skyldes adferdsendringer, konjunktursvingninger, omstillinger på arbeidsmarkedet eller at det har skjedd andre endringer i befolkningen enn alderssammensetningen (for eksempel endret utdanningsnivå, endret helse eller endringer i andelen innvandrere). Endringer i utbetalingene per mottaker kan eksempelvis skyldes endringer i hvor hyppig ulike inntektsgrupper i befolkningen mottar de ulike ytelsene eller endringer i sysselsettingen (som for eksempel påvirker pensjonsopptjeningen for alderspensjon).
:::

Usikkerhet i framskrivingene

Framskrivingene er usikre. Befolkningsendringer er den viktigste faktoren i de langsiktige framskrivingene. Utviklingen i perioden 2015–2025 viser likevel at utgiftsutviklingen på enkeltområder kan avvike vesentlig fra hva befolkningsendringene tilsier, for eksempel på grunn av faktorer som konjunktursvingninger, endret helse, teknologisk utvikling (som har betydning for hjelpemidler og legemidler) og andre forhold. Befolkningsutviklingen er også usikker, særlig når det gjelder fødselstall og innvandring, mens den er mer forutsigbar når det gjelder utviklingen i antall eldre. Konsekvensene av befolkningsusikkerhet varierer derfor mellom de ulike ytelsene.

I tillegg er det betydelig usikkerhet omkring framtidige effekter av større regelendringer. Det gjelder blant annet de mange endringene i reglene for arbeidsavklaringspenger i perioden 2018–2022, som ventes å gi effekter fram mot 2026. Effektene av pensjonsreformen og pensjonsforliket er også usikre, særlig når det gjelder hvordan uttaksalderen for alderspensjon vil utvikle seg. I hvilken grad avgangsalderen fra arbeidslivet vil fortsette å øke, har også en viss betydning.

